// Button texts
export const BUTTONS = {
  // Common actions
  SAVE: 'حفظ',
  CANCEL: 'إلغاء',
  DELETE: 'حذف',
  EDIT: 'تعديل',
  CREATE: 'إضافة',
  REMOVE: 'إزالة',
  CONFIRM: 'تأكيد',
  BACK: 'رجوع',
  NEXT: 'التالي',
  PREVIOUS: 'السابق',
  CLOSE: 'إغلاق',
  UPDATE: 'تحديث',
  SUBMIT: 'إرسال',
  SEARCH: 'بحث',
  FILTER: 'فلتر',
  RESET: 'إعادة تعيين',
  REFRESH: 'تحديث',
  SEND_OTP: 'إرسال رمز التحقق',
  SENDING: 'جاري الإرسال...',
  UPDATING: 'جاري التحديث...',
  UPDATE_PASSWORD: 'تحديث كلمة المرور',
  RESEND_CODE: 'إعادة إرسال الرمز',
  BACK_TO_LOGIN: 'العودة لتسجيل الدخول',

  // Specific actions
  ADD_CATEGORY: 'إضافة فئة جديدة',
  ADD_PRODUCT: 'إضافة منتج جديد',
  ADD_VARIANT: 'إضافة متغير',
  REMOVE_VARIANT: 'حذف متغير',
  ADD_ADDRESS: 'إضافة عنوان جديد',
  ADD_TO_CART: 'إضافة للسلة',
  BUY_NOW: 'اشترِ الآن',
  VIEW_CART: 'عرض السلة',
  CHECKOUT: 'إتمام الشراء',
  COMPLETE_ORDER: 'إتمام الطلب',
  CONTINUE_SHOPPING: 'مواصلة التسوق',
  VIEW_DETAILS: 'عرض التفاصيل',
  VIEW_ALL: 'عرض الكل',
  SHOW_MORE: 'عرض المزيد',
  SHOW_LESS: 'عرض أقل',
  SAVE_CHANGES: 'حفظ التغييرات',
  UPDATE_ROLES: 'تحديث الأدوار',
  RETRY_PAYMENT: 'إعادة المحاولة',
  VIEW_MY_ORDERS: 'عرض طلباتي',
  BACK_TO_PRODUCTS: 'العودة للمنتجات',
  BROWSE_PRODUCTS: 'تصفح المنتجات',
  UPLOAD_IMAGE: 'رفع صورة',
  SIGN_IN: 'تسجيل الدخول',
  SIGN_UP: 'إنشاء حساب',
  SIGN_OUT: 'تسجيل الخروج',
  CHANGE_PASSWORD: 'تغيير كلمة المرور',
  UPDATE_STATUS: 'تحديث الحالة',
  APPLY_CHANGES: 'تطبيق التغييرات',
  GO_HOME: 'العودة للرئيسية',
  TRY_AGAIN: 'حاول مرة أخرى',
  BACK_TO_ORDERS: 'العودة للطلبات',

  // Cart related
  INCREASE_QUANTITY: 'زيادة الكمية',
  DECREASE_QUANTITY: 'تقليل الكمية',
  REMOVE_FROM_CART: 'إزالة من السلة',
  CLEAR_CART: 'تفريغ السلة',

  // Pagination
  PAGE_NEXT: 'التالي',
  PAGE_PREV: 'السابق',

  // Admin buttons
  BACK_TO_STORE: 'العودة للمتجر',
  ADMIN_DASHBOARD: 'لوحة الإدارة',

  // Complete order
  COMPLETE_ORDER_PROCESSING: 'جاري معالجة الطلب...',
};
